FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt pyproject.toml ./
COPY ml ./ml
COPY apps ./apps
COPY artifacts ./artifacts
COPY data ./data

RUN python -m pip install --upgrade pip \
  && pip install -r requirements.txt \
  && pip install -e .

EXPOSE 8000

CMD ["uvicorn", "apps.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

